# Generated by Django 5.0.4 on 2024-04-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_currencyrate_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10),
        ),
    ]
