# Generated by Django 5.0.4 on 2024-05-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_currencyrate_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
    ]
