# Generated by Django 5.0.4 on 2024-05-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_currencyrate_exchange_rate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='currencyrate',
            index=models.Index(fields=['currency_code'], name='api_currenc_currenc_c0b746_idx'),
        ),
    ]
